import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // Hobby track — new in v0.8.
  hobbySidebar: [
    'hobby/hobby-index',
    'hobby/big-idea',
    'hobby/identify-unknown-connector',
    'hobby/jst-is-not-one-connector',
    'hobby/bad-listing-examples',
    'hobby/pitch',
    {
      type: 'category',
      label: 'Common Hobby Connector Families',
      link: {type: 'doc', id: 'hobby/families'},
      collapsed: false,
      items: [
        'hobby/dupont-headers',
        'hobby/servo-connectors',
        'hobby/jst-xh',
        'hobby/jst-ph',
        'hobby/jst-sh-qwiic-stemma',
        'hobby/jst-gh',
        'hobby/jst-sm-led-connectors',
        'hobby/xt-connectors',
        'hobby/rc-battery-connectors',
        'hobby/anderson-powerpole',
        'hobby/barrel-jacks',
        'hobby/screw-terminals',
        'hobby/usb-c-power',
      ],
    },
    'hobby/power-vs-signal',
    'hobby/crimping',
    'hobby/connector-kits',
    'hobby/buying-mating-parts',
    'hobby/when-hobby-is-not-enough',
    'shared/hobby-or-professional',
    'hobby/decision-guide',
    'hobby/hobby-source-notes',
    // type:'ref' links to docs owned by guideSidebar without changing their
    // sidebar association — and resolves baseUrl-safely, unlike raw hrefs.
    {
      type: 'ref',
      id: 'shared/glossary',
      label: 'Glossary (shared)',
    },
    {
      type: 'ref',
      id: 'shared/connector-identification',
      label: 'Identification Workflow (shared)',
    },
  ],

  // Professional / industrial track — the original guide, URLs unchanged.
  // The site root (docs/index.md) is the two-track landing page and is
  // intentionally in no sidebar.
  guideSidebar: [
    'engineering/engineering-home',
    {
      type: 'category',
      label: 'Start Here',
      collapsed: false,
      items: ['engineering/guide/00-how-to-search-for-connectors'],
    },
    {
      type: 'category',
      label: 'Decision Paths',
      link: {type: 'doc', id: 'decision-paths/decision-paths-index'},
      collapsed: false,
      items: [
        'decision-paths/industrial-sensor',
        'decision-paths/motor-feedback-cable',
        'decision-paths/rugged-ethernet',
        'decision-paths/internal-pcb-harnessing',
        'decision-paths/board-to-board',
        'decision-paths/rugged-on-a-budget',
        'decision-paths/high-current-dc-power',
        'decision-paths/sealed-enclosure-feedthrough',
        'decision-paths/debug-service-port',
        'decision-paths/micro-d',
        'decision-paths/defense-rugged-external-io',
        'decision-paths/removable-machine-module',
        'decision-paths/rf-gps-radio',
      ],
    },
    {
      type: 'category',
      label: 'Guide',
      collapsed: false,
      items: [
        'engineering/guide/01-what-connectors-do',
        'engineering/guide/02-major-connector-categories',
        'engineering/guide/03-connector-standards-and-families',
        'engineering/guide/04-connector-selection-workflow',
        'engineering/guide/05-connector-anatomy',
        'engineering/guide/06-reading-datasheets',
        'engineering/topics/low-level-signal-contacts',
        'engineering/families/07-mil-dtl-38999',
        'engineering/families/mil-dtl-26482',
        'engineering/families/08-m12',
        'engineering/families/deutsch',
        'engineering/guide/09-decision-examples',
        'engineering/guide/10-selection-checklist',
        'engineering/guide/11-red-flags',
        'engineering/topics/lifecycle-and-procurement',
        'engineering/guide/12-consumer-hobby-prototype-connectors',
        'engineering/families/micro-fit',
        'engineering/guide/13-hands-on-exercises',
        'engineering/guide/14-thirty-day-learning-plan',
      ],
    },
    'engineering/guide/what-people-forget',
    'shared/connector-identification',
    'shared/glossary',
    {
      type: 'category',
      label: 'Tools & Templates',
      link: {type: 'doc', id: 'tools/tools-index'},
      collapsed: false,
      items: [
        'tools/connector-selection-checklist',
        'tools/connector-comparison-matrix',
        'tools/cable-drawing-template',
        'tools/connector-icd-template',
        'tools/design-review-checklist',
        'tools/m12-coding-cheat-sheet',
        'tools/decode-38999-worksheet',
        'tools/deutsch-decode-worksheet',
        'tools/harness-inspection-checklist',
        'tools/connector-qualification-template',
      ],
    },
    {
      type: 'category',
      label: 'Examples',
      link: {type: 'doc', id: 'examples/examples-index'},
      collapsed: false,
      items: [
        'examples/rugged-control-box',
        'examples/connector-selection-packet',
        'examples/m12-sensor-interface',
      ],
    },
    'engineering/guide/using-this-guide-with-an-intern',
    {
      type: 'category',
      label: 'Appendix',
      collapsed: false,
      items: [
        'appendix/quick-reference-tables',
        'appendix/source-notes',
        'shared/image-attributions',
        'project/image-opportunities',
      ],
    },
    'shared/usage-and-attribution',
  ],
};

export default sidebars;
